spring:
  application:
    name: kalaha
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:kalaha;INIT=CREATE SCHEMA IF NOT EXISTS kalaha;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  port: 8080

springdoc:
  packagesToScan: "com.game.kalaha"
  pathsToMatch: "/**"

pits: 6
stones: 6